ci-cd:
  - changed-files:
      - any-glob-to-any-file: .github/**

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - requirements/*.txt
          - requirements.txt

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**
          - requirements/documentation.txt

packaging:
  - head-branch:
    - "^packaging"
    - packaging
  - changed-files:
    - any-glob-to-any-file:
      - requirements/packaging.txt
      - setup.py

quality:
  - changed-files:
      - any-glob-to-any-file:
        - tests/**/*

tooling:
  - head-branch: ["^tooling", "tooling"]
  - changed-files:
      - any-glob-to-any-file:
          - .vscode/*
          - .pre-commit-config.yaml
          - setup.cfg
